weatherSource:
  - ==: cx.rain.mc.timesync.data.WeatherSource
    name: hefeng
    type: HE_FENG_FREE
    key: ''
    longitude: 116.00
    latitude: 39.00
    updateInterval: 3600

timeSource:
  - ==: cx.rain.mc.timesync.data.TimeSource
    name: local
    type: LOCAL
    timeZone: Asia/Shanghai
    updateInterval: 3600

weatherSyncWorld:
  world: hefeng

timeSyncWorld:
  world: local
